# GoogLeNet model and training hyperparameters

# Learning Parameters
n_epochs: 90 # def: 70 for  AlexNet, 90 for GoogLeNet
learning_rate: 0.005  # def: 0.01 for both AlexNet and GoogLeNet

# Weight Decay
weight_decay: 0.0002 # def: 0.0005 for AlexNet, 0.0002 for GoogLeNet

# Momentum
momentum: 0.9 # def: 0.9

# Model info
name: googlenet
input_width: 224 # def: 227 for AlexNet, 224 for GoogLeNet 
input_height: 224 # def: 227 for AlexNet, 224 for GoogLeNet 

n_softmax_out: 1000

batch_size: 32 # def: 128 # def: 128 for AlexNet, 32 for GoogleNet 

image_mean: img_mean
